### ISSUE TITLE
'decode' is not exported from '@ipld/dag-cbor'

### ISSUE THREAD

**Issue by luizoamorim** [ipld/js-dag-cbor#37] opened 2021-08-30 20:55 UTC
I'm using nft.storage in my project. This library have ipld dependence.

I've got this error when I try generate a project build:

**./node_modules/@ipld/car/esm/lib/decoder.js
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').**

Can somebody help me?

**Comment by rvagg** [comment] 2021-09-02 05:02
What environment are you trying to build and run this in @luizoamorim? This wouldn't be Jest would it? You're possibly using an environment that doesn't support export maps properly but there should be workarounds.

**Comment by sicktastic** [comment] 2021-09-15 18:56
I got the same error using nft.storage with next.js and it fails during build time.  Did anyone found the workaround yet?

**Comment by rvagg** [comment] 2021-09-16 01:39
Can you provide some code to reproduce this? We have a lot of folks (including myself for percid.va.gg) using this code directly via next.js and other frameworks and nft.storage and web3.storage without these problems, so there must be something specific about the environment that's causing a hiccup. Can you describe the toolchain and setup in a way that might help us narrow it down?

**Comment by fungilation** [comment] 2021-10-04 00:05
I'm stuck with this issue. TLDR of https://github.com/ipfs-shipyard/nft.storage/issues/215#issuecomment-932806972: I have to downgrade `nft.storage` from 3.x to 2.x, in order to completely avoid the `@ipld/dag-cbor` dependency. Otherwise, I find no other way to avoid `next build` error:

```
$ npm run build

> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Creating an optimized production build
Failed to compile.

./node_modules/@ipld/car/esm/lib/decoder.js
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').


> Build error occurred
Error: > Build failed because of webpack error
```

My package.json:
```
{
  ...
  "dependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts": "^4.3.1",
    "axios": "^0.21.4",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.6",
    "hardhat": "^2.6.4",
    "moralis": "^0.0.67",
    "next": "11.1.2",
    "nft.storage": "^2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-moralis": "^0.2.3",
    "web3modal": "^1.9.4"
  },
  "devDependencies": {
    "@types/node": "^16.6.1",
    "@types/react": "^17.0.15",
    "@types/react-dom": "^17.0.9",
    "@types/react-redux": "^7.1.18",
    "autoprefixer": "^10.3.4",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.2",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "postcss": "^8.3.6",
    "prettier": "^2.3.2",
    "stylelint": "^13.13.1",
    "stylelint-config-recommended": "^5.0.0",
    "tailwindcss": "^2.2.15",
    "ts-node": "^10.2.0",
    "typescript": "4.4.3"
  }
}
```

**Comment by rvagg** [comment] 2021-10-04 05:52
If someone experiencing this can provide a very simple reproduction they can share, maybe just a basic project that doesn't build, shared as a repo or some other way, that would be extremely helpful in narrowing this down. Having to support so many permutations of build environment makes this a bit tricky to isolate without help.

**Comment by theshadowagent** [comment] 2021-11-05 02:36
Still running into this with `next.js`, any update?

**Comment by rvagg** [comment] 2021-11-05 10:50
@achingbrain suspected this might be related to https://github.com/webpack/webpack/discussions/14268 which was about a very similar problem in our stack.

https://github.com/webpack/enhanced-resolve/issues/304 is related and lead to https://github.com/webpack/enhanced-resolve/pull/305 in enhanced-resolve.

I've used @LAMike310's suggestion for how to replicate the problem (with js-ipfs-browser-nextjs - can confirm, it breaks, thanks @LAMike310!), and have applied the fix for enhanced-resolve's `getInnerRequest` to `./node_modules/next/dist/compiled/webpack/bundle5.js`, and after deleting .next/cache/ and re-running the build, it works.

So it's to do with our heavy reliance on export maps and the `"."` (implicit and explicit) mapping we have in our various packages that use this same pattern. I'm not quite sure how differences in npm vs yarn vs package-lock.json etc. come in to play as has been mentioned in the various threads about this topic. Something to do with relative path from importer to exporter I suppose—I don't know how that relates to export maps though!

So enhanced-resolve has a fix. But unfortunately that needs to bubble from there to webpack and to nextjs. And as mentioned in https://github.com/webpack/enhanced-resolve/issues/304#issuecomment-925685401, it's not going to be backported.

**Comment by theshadowagent** [comment] 2021-11-05 23:32
I just updated `next` from `11.1.2` to `12`, deleted `.next` and `yarn.lock`, and the problem went away

**Comment by rvagg** [comment] 2022-04-05 21:55
closing because this seems to have been fixed by toolchain updates

**Closed by rvagg** 2022-04-05 21:55 UTC
